name: Create Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
    - name: Run gh release create
      run: |
        gh release create ${GITHUB_REF/refs\/tags\//} -t ${GITHUB_REF/refs\/tags\//}
